blank_issues_enabled: false
contact_links:
  - name: å‰å¾€è®¨è®ºåŒº (ğŸ’¬ Discussions)
    url: https://github.com/XIU2/CloudflareSpeedTest/discussions
    about: Issues ä»…ç”¨äºåé¦ˆé—®é¢˜ã€åŠŸèƒ½å»ºè®®ï¼Œå…¶ä»–è¯é¢˜è¯·åˆ° ğŸ’¬ Discussions å‘å¸–è®¨è®ºï¼ˆä¸åˆé€‚çš„ Issues ä¼šè¢«è½¬è¿‡å»